blank_issues_enabled: false
contact_links:
  - name: End-user/Community Support
     url: https://github.com/code4recovery/12-step-meeting-list/discussions/categories/q-a
     about: Please ask and answer questions here.
